services:
  rclonebrowser_service:
    image: ghcr.io/quyentruong/rclonebrowser-docker:latest
    container_name: rclonebrowser
    ports:
      - "5804:5800"
    environment:
      - USER_ID=0
      - GROUP_ID=0
      - TZ=America/Los_Angeles
      - KEEP_APP_RUNNING=1
      - SECURE_CONNECTION=1
      - VNC_PASSWORD=password
    volumes:
      - "/share/Container/rclonebrowser:/config:rw"
      - "/share/Container/rclonebrowser/shared:/shared:rw"
